# Generated by Django 4.2 on 2024-12-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_firstname_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
